create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  order_number text not null unique,
  first_name text not null,
  last_name text not null,
  phone text not null,
  address text not null,
  locality text not null,
  observations text,
  payment_method text not null,
  status text not null default 'Pendiente',
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  is_new boolean not null default true,
  constraint orders_status_check check (
    status in ('Pendiente', 'Confirmado', 'Preparando', 'Enviado', 'Entregado', 'Cancelado')
  )
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint,
  product_name text not null,
  product_image text,
  size text not null,
  quantity integer not null check (quantity > 0),
  unit_price_cash numeric(12, 2) not null check (unit_price_cash >= 0),
  unit_price_card numeric(12, 2) not null check (unit_price_card >= 0),
  subtotal_amount numeric(12, 2) not null check (subtotal_amount >= 0)
);

create or replace function public.assign_order_number()
returns trigger
language plpgsql
as $$
begin
  if new.order_number is null or btrim(new.order_number) = '' then
    new.order_number := 'PED-' || lpad(new.id::text, 6, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists set_order_number_on_orders on public.orders;

create trigger set_order_number_on_orders
before insert on public.orders
for each row
execute function public.assign_order_number();

create or replace function public.create_order_with_items(
  order_payload jsonb,
  items_payload jsonb
)
returns public.orders
language plpgsql
as $$
declare
  created_order public.orders;
begin
  insert into public.orders (
    first_name,
    last_name,
    phone,
    address,
    locality,
    observations,
    payment_method,
    total_amount
  )
  values (
    coalesce(order_payload->>'first_name', ''),
    coalesce(order_payload->>'last_name', ''),
    coalesce(order_payload->>'phone', ''),
    coalesce(order_payload->>'address', ''),
    coalesce(order_payload->>'locality', ''),
    nullif(order_payload->>'observations', ''),
    coalesce(order_payload->>'payment_method', 'WhatsApp'),
    coalesce((order_payload->>'total_amount')::numeric, 0)
  )
  returning * into created_order;

  insert into public.order_items (
    order_id,
    product_id,
    product_name,
    product_image,
    size,
    quantity,
    unit_price_cash,
    unit_price_card,
    subtotal_amount
  )
  select
    created_order.id,
    nullif(item->>'product_id', '')::bigint,
    coalesce(item->>'product_name', ''),
    nullif(item->>'product_image', ''),
    coalesce(item->>'size', ''),
    coalesce((item->>'quantity')::integer, 1),
    coalesce((item->>'unit_price_cash')::numeric, 0),
    coalesce((item->>'unit_price_card')::numeric, 0),
    coalesce((item->>'subtotal_amount')::numeric, 0)
  from jsonb_array_elements(items_payload) as item;

  return created_order;
end;
$$;

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can insert orders" on public.orders;
create policy "Public can insert orders"
on public.orders
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated can read orders" on public.orders;
create policy "Authenticated can read orders"
on public.orders
for select
to authenticated
using (true);

drop policy if exists "Authenticated can update orders" on public.orders;
create policy "Authenticated can update orders"
on public.orders
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete orders" on public.orders;
create policy "Authenticated can delete orders"
on public.orders
for delete
to authenticated
using (true);

drop policy if exists "Public can insert order items" on public.order_items;
create policy "Public can insert order items"
on public.order_items
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated can read order items" on public.order_items;
create policy "Authenticated can read order items"
on public.order_items
for select
to authenticated
using (true);

drop policy if exists "Authenticated can update order items" on public.order_items;
create policy "Authenticated can update order items"
on public.order_items
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete order items" on public.order_items;
create policy "Authenticated can delete order items"
on public.order_items
for delete
to authenticated
using (true);

grant execute on function public.create_order_with_items(jsonb, jsonb) to anon, authenticated;