create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  nombre text not null unique
);

insert into public.categorias (nombre)
values
  ('Botas'),
  ('Sandalias'),
  ('Vestidos'),
  ('Pantalones'),
  ('Abrigos'),
  ('Sobres de Fiesta')
on conflict (nombre) do nothing;

alter table public.categorias enable row level security;

drop policy if exists "Authenticated can read categorias" on public.categorias;
create policy "Authenticated can read categorias"
on public.categorias
for select
to authenticated
using (true);