do $$
begin
  if to_regclass('public.orders') is not null and to_regclass('public.pedidos') is null then
    alter table public.orders rename to pedidos;
  end if;

  if to_regclass('public.order_items') is not null and to_regclass('public.pedido_items') is null then
    alter table public.order_items rename to pedido_items;
  end if;
end
$$;

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  order_number text not null unique,
  first_name text not null,
  last_name text not null,
  phone text not null,
  address text not null,
  locality text not null,
  observations text,
  payment_method text not null,
  status text not null default 'Pendiente',
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  is_new boolean not null default true,
  constraint pedidos_status_check check (
    status in ('Pendiente', 'Confirmado', 'Preparando', 'Enviado', 'Entregado', 'Cancelado')
  )
);

create table if not exists public.pedido_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  product_id bigint,
  product_name text not null,
  product_image text,
  size text not null,
  quantity integer not null check (quantity > 0),
  unit_price_cash numeric(12, 2) not null check (unit_price_cash >= 0),
  unit_price_card numeric(12, 2) not null check (unit_price_card >= 0),
  subtotal_amount numeric(12, 2) not null check (subtotal_amount >= 0)
);

create or replace function public.assign_order_number()
returns trigger
language plpgsql
as $$
begin
  if new.order_number is null or btrim(new.order_number) = '' then
    new.order_number := 'PED-' || lpad(new.id::text, 6, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists set_order_number_on_pedidos on public.pedidos;
create trigger set_order_number_on_pedidos
before insert on public.pedidos
for each row
execute function public.assign_order_number();

create or replace function public.create_pedido_with_items(
  order_payload jsonb,
  items_payload jsonb
)
returns public.pedidos
language plpgsql
as $$
declare
  created_order public.pedidos;
begin
  insert into public.pedidos (
    first_name,
    last_name,
    phone,
    address,
    locality,
    observations,
    payment_method,
    total_amount
  )
  values (
    coalesce(order_payload->>'first_name', ''),
    coalesce(order_payload->>'last_name', ''),
    coalesce(order_payload->>'phone', ''),
    coalesce(order_payload->>'address', ''),
    coalesce(order_payload->>'locality', ''),
    nullif(order_payload->>'observations', ''),
    coalesce(order_payload->>'payment_method', 'WhatsApp'),
    coalesce((order_payload->>'total_amount')::numeric, 0)
  )
  returning * into created_order;

  insert into public.pedido_items (
    pedido_id,
    product_id,
    product_name,
    product_image,
    size,
    quantity,
    unit_price_cash,
    unit_price_card,
    subtotal_amount
  )
  select
    created_order.id,
    nullif(item->>'product_id', '')::bigint,
    coalesce(item->>'product_name', ''),
    nullif(item->>'product_image', ''),
    coalesce(item->>'size', ''),
    coalesce((item->>'quantity')::integer, 1),
    coalesce((item->>'unit_price_cash')::numeric, 0),
    coalesce((item->>'unit_price_card')::numeric, 0),
    coalesce((item->>'subtotal_amount')::numeric, 0)
  from jsonb_array_elements(items_payload) as item;

  return created_order;
end;
$$;

alter table public.pedidos enable row level security;
alter table public.pedido_items enable row level security;

drop policy if exists "Public can insert pedidos" on public.pedidos;
create policy "Public can insert pedidos"
on public.pedidos
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated can read pedidos" on public.pedidos;
create policy "Authenticated can read pedidos"
on public.pedidos
for select
to authenticated
using (true);

drop policy if exists "Authenticated can update pedidos" on public.pedidos;
create policy "Authenticated can update pedidos"
on public.pedidos
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete pedidos" on public.pedidos;
create policy "Authenticated can delete pedidos"
on public.pedidos
for delete
to authenticated
using (true);

drop policy if exists "Public can insert pedido items" on public.pedido_items;
create policy "Public can insert pedido items"
on public.pedido_items
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated can read pedido items" on public.pedido_items;
create policy "Authenticated can read pedido items"
on public.pedido_items
for select
to authenticated
using (true);

drop policy if exists "Authenticated can update pedido items" on public.pedido_items;
create policy "Authenticated can update pedido items"
on public.pedido_items
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete pedido items" on public.pedido_items;
create policy "Authenticated can delete pedido items"
on public.pedido_items
for delete
to authenticated
using (true);

grant execute on function public.create_pedido_with_items(jsonb, jsonb) to anon, authenticated;